### ISSUE TITLE
Package Control Support

### ISSUE THREAD

**Issue by Jax0rz** [sublimelsp/LSP-typescript#1]
Please make this work with Package Control

**Comment by predragnikolic** [comment]
That's is my end goal. 

But I am having trouble getting eslint and tslint server working with lsp-tsserver :-)

I will keep you updated.

**Comment by GlassGruber** [comment]
Hey there sorry for bumping this but the readme suggests to install the plugin via package control and I can't find `LSP-typescript`. 
Am I missing something?

Thank you!

**Comment by predragnikolic** [comment]
No, it is still not published on package control. :-)

You can read more about the why it's not on package control yet here: wbond/package_control_channel#7727 (comment) sublimelsp/LSP#854 (comment)

**Comment by GlassGruber** [comment]
Oh I see interesting.

If anyone needs, I've installed the plugin by adding the git repository address via `Package Control: Add Repository` in the command palette. 

Do you see any side effects with it?

Thank you

**Comment by predragnikolic** [comment]
No, I don't see any bad side effect :-)

**Comment by predragnikolic** [comment]
https://packagecontrol.io/packages/LSP-typescript

It is published 🙂
