### ISSUE TITLE
1.5.0+ is incompatible with Sublime Text 3

### ISSUE THREAD

**Issue by Narretz** [sublimelsp/LSP-typescript#106]
Ever since the findCallers functionality was introduced, the plugin is not compatible with Sublime Text 3 anymore, because the ST3 version of LSP doesn't have a lot of exports used by LSP-typescript.

See the protocol.py in this commit: https://github.com/sublimelsp/LSP-typescript/commit/bc814efc1afeb1b92718769b6b69c37f62f4f1f8#diff-0b549f1c0f3a521812a4528e268dfa59241bac5f2e69ff8a3c745f75a7fdc981

And the corresponding LSP.plugin.core.protocol at the latest ST3 version: https://github.com/sublimelsp/LSP/blob/3154-0.14.3/plugin/core/protocol.py

Since I don't see anything official about ST3 support being dropped, I think this should be fixed.

Possible solutions:
- different releases for ST3 and ST4
- make the new features compatible with ST3
- disable the new features in ST3
- drop support for ST3

**Comment by rchl** [comment]
I'll create a new branch and new release for ST3 from an older commit as I don't want to spend effort on maintaining ST3 support.

**Comment by Narretz** [comment]
Works for me, thanks!

**Comment by rchl** [comment]
ST3-compatible should appear in about 2h from now.

**Comment by Narretz** [comment]
Hi @rchl the release is on package-control but the commit it's built from points to master which means it's basically the same aas 1.8.0: 
Release: https://github.com/sublimelsp/LSP-typescript/releases/tag/st3-1.9.0
Commit: https://github.com/sublimelsp/LSP-typescript/commit/59b60921a81cb13b8f6d73472bc91e3ef4d34f53

**Comment by rchl** [comment]
Thanks for catching that. Fixed now.
