### ISSUE TITLE
Auto format the code with Single Quotes

### ISSUE THREAD

**Issue by zhandosweb** [sublimelsp/LSP-typescript#111]
Hello! 

I'm first time installing LSP and LSP server language packages for Sublime Text, and very happy with those packages. I try to move from VS Code to Sublime, and try to get same experience. 

I have 2 questions, that I faced now, can I ask my questions here, please? 

1. Can I force to use Single Quotes in my javascript files, when I save the edited .js files? I mean auto-format the saved files and replace double "" quotes with single ''. 

2. Is LSP-Typescript plugin able to remove empty spaces within my .js file? It's also about auto formatting the code after saving edited files. 

In VS Code I'm using Prettier plugin, and Prettier auto formatting all those things above automatically (removing empty spaces, replacing double quotes to single, etc). And maybe I should use other extra plugin to formatting my .js files, but better, if it can be fixed with LSP plugins. 

Sorry for my bad English, I believe you understand me. And thank you for all LSP team, amazing plugins giving me pleasure experience for coding.

**Comment by rchl** [comment]
This package is not concerned with linting but the https://github.com/sublimelsp/LSP-eslint can be used to fix spaces and quotes when configured properly.

**Comment by zhandosweb** [comment]
> This package is not concerned with linting but the https://github.com/sublimelsp/LSP-eslint can be used to fix spaces and quotes when configured properly.

Sorry, can you tell me. Does LSP-typescript package support formatting .js files? Or only linting javascript code? I'm a little bit confused. 

Because, when I saved my files, code will format automatically, and that's because of package LSP-typescript, right? Or this function is built in Sublime Text 4? Sorry for noob questions.

**Comment by rchl** [comment]
It's not really about linting but about type-checking.

It does provide some basic formatting abilities but nothing that you can rely on to fix your code to be consistent. For that you should configure `eslint` and use `LSP-eslint`. Or prettier (personally not a fan).

**Comment by zhandosweb** [comment]
Thank you so much for the answers! Please, sir, let me ask the last question.

I see there is a command LSP: Format File. And LSP packages may format the files, but you said there are only basic features for formatting. 

If I install another plugin for formatting (`LSP-eslint` or `prettier`), these plugins can go along together? Or I should disable auto-formatting first (I'm using now 2 plugins: `LSP-html` and `LSP-typescript`), and then configure another plugin for formatting?

**Comment by rchl** [comment]
`LSP-typescript` barely does any formatting so I don't think it would conflict.

`LSP-eslint` applies the changes through Code Actions (refer to its readme) so it doesn't need formatting to be enabled. And if there are conflicts then you can disable LSP formatting on save.
