### ISSUE TITLE
how to Generates parentheses when calling a function

### ISSUE THREAD

**Issue by AirBashX** [sublimelsp/LSP-typescript#113]
For example:

document.getElementsByName
                     ||
document.getElementsByName()

**Comment by rchl** [comment]
This functionality is supported by the server but unfortunately ST doesn't allow us to utilize it. We'd need https://github.com/sublimehq/sublime_text/issues/3298 to be implemented for that to work.

**Comment by rchl** [comment]
I'll close this issue since it would have to be solved in `LSP` package instead if the ST API is implemented.

**Comment by predragnikolic** [comment]
LSP knows what lsp completion item is selected. So that would not be a problem.

This would not work only if the server is modifying the completion item textEdit or insertText in resolve request.

**Comment by rchl** [comment]
That's the case here. The extra data that we need is provided through the resolve request. We'd want to resolve that on focusing given completion in the list but we can't. In theory it would be possible to do that before completion is inserted but that introduces too much latency.
