### ISSUE TITLE
Only close the `hint` and `show_code_actions` of the `lsp-typescript` package

### ISSUE THREAD

**Issue by thep0y** [sublimelsp/LSP-typescript#114]
I am using `lsp-eslint` and `lsp-typescript`, these two packages will generate the same `hint` and `code_actions` for the code.
<img width="986" alt="image" src="https://user-images.githubusercontent.com/51874567/145966242-18875280-bae2-40b0-9e7d-bc0820450334.png">

I just want to keep the `hint` and `code_actions` of `lsp-eslint`. What should I do?

**Comment by rchl** [comment]
There is a `diagnostics.ignoredCodes` settings in LSP-typescript. You can ignore specific codes with it. In this case `6133`.

**Comment by thep0y** [comment]
> There is a `diagnostics.ignoredCodes` setting in LSP-typescript. You can ignore specific codes with it (in this case `6133`).

```json
{
    "settings": {
        "diagnostics.ignoredCodes": [
            6133
        ],
    }
}
```

Now it is working as I expected, thank you.
