### ISSUE TITLE
Incorrect Action in Readme's "Code Actions On Save" Section

### ISSUE THREAD

**Issue by EthanHipps** [sublimelsp/LSP-typescript#123]
Hello,

I noticed that the "Add Missing Imports" action, `source.addMissingImports.ts`, listed in the Readme's "Code Actions On Save" section doesn't match what LSP logs in the output window, `source.SourceAddMissingImportsTs.ts`. 

I tested both and only `source.SourceAddMissingImportsTs.ts` worked for me.

Here's a screenshot of the LSP log.
<img width="974" alt="image" src="https://user-images.githubusercontent.com/13156894/149208577-7a3ac41e-ae0b-4ba1-87fc-bcf0cd391d30.png">

**Comment by rchl** [comment]
It needs to fixed in https://github.com/typescript-language-server/typescript-language-server but I'll keep this open until the server version with the fix is pulled in. Thaks.

**Comment by rchl** [comment]
Fixed in https://github.com/sublimelsp/LSP-typescript/releases/tag/1.10.1

**Comment by EthanHipps** [comment]
Awesome. Thanks!
