### ISSUE TITLE
Plugin is overriding tab key behavior for tabnine

### ISSUE THREAD

**Issue by caseycole589** [sublimelsp/LSP-typescript#124]
Normally when using tabnine I can keep hitting the tab key to go to the next autocomplete suggestion. This plugin is overriding this behavior. When hitting the tab key now the first suggestion is always selected. I can't figure out where how to override this.  Is there a setting some where I am missing?

**Comment by rchl** [comment]
Not sure what you mean. Can you post a video showing the issue?

Neither this package nor LSP overrides the tab key and the default behavior of ST is to complete the suggestion on `tab`.

**Comment by rwols** [comment]
Is perhaps tabnine overriding your tab key instead? https://github.com/codota/tabnine-sublime/blob/1a2f4750d7b912329ff35068655ff9018f1112ec/Default.sublime-keymap#L2
