### ISSUE TITLE
Can I configure LSP ignore directories/files?

### ISSUE THREAD

**Issue by onsi** [sublimelsp/LSP-typescript#132]
Hey there,  possibly dumb question here but I haven't manage to figure this out...

I'm pulling a number of third-party libraries into my source tree and some of them are generating lsp-typescript hints in the ST4 LSP pane.  Is there a way to configure asp-typescript (or lsp more broadly) to ignore files and/or folders?

**Comment by rchl** [comment]
Maybe not doable the way you are thinking but you can configure typescript with `tsconfig` file so you could potentially created a nested `tsconfig.json` in a "third-party" directory and disable type checking for that directory (possibly by disabling [checkJs](https://www.typescriptlang.org/tsconfig#checkJs)).

**Comment by onsi** [comment]
got it thanks, will give it a try and report back.

**Comment by onsi** [comment]
looks like the diagnostics only appear if I happen to have the third-party file open in a sublime text tab.  closing this out.
