### ISSUE TITLE
why it import from minified react not just react?

### ISSUE THREAD

**Issue by sirlaurie** [sublimelsp/LSP-typescript#143]
Sublime Text 4, Build 4131
LSP v1.16.2
LSP-typescript v1.10.5
with default preferences

<img width="603" alt="image" src="https://user-images.githubusercontent.com/8928155/168629635-8dcb8dc7-be1b-43ca-be37-a8521d3ea46f.png">

**Comment by rchl** [comment]
If you can reproduce in VSCode then I'd suggest asking at https://github.com/microsoft/TypeScript

**Comment by sirlaurie** [comment]
I found a solution on stackoverflow
`npm install @types/react`
and it does work.
