### ISSUE TITLE
LSP-typescript: The system Node.js does not meet the requirements

### ISSUE THREAD

**Issue by ravshansbox** [sublimelsp/LSP-typescript#149]
LSP-typescript: The system Node.js does not meet the requirements: NodeRuntimePATH(node: None, npm: None, version: None)

Tried with volta and nvm in macOS.

calling `which node` in the shell is showing proper path for node.
node and npm executable are running properly.

**Comment by rchl** [comment]
See https://lsp.sublimetext.io/troubleshooting/#updating-the-path-used-by-lsp-servers on how to fix PATH in ST.

**Comment by predragnikolic** [comment]
Closing this because this issue seems stale.
@ravshansbox if you didn't manage to resolve your issue feel free to reopen this
