### ISSUE TITLE
extension not working after installing

### ISSUE THREAD

**Issue by lallenfrancisl** [sublimelsp/LSP-typescript#15]
Do I have to install language servers even after installing this.

But even after installing and specifying the language server it still does not work. In the beginning it shows `LSP Initialised` but does not work afterward. I have tried all of the language servers specified in the how to. Is there something I am missing.

Ubuntu 20.04
Sublime Text 3 Build 3211

**Comment by predragnikolic** [comment]
Can you close sublime. 
And reopen it.
Can you copy the contents of the sublime console(ctrl+`)
and paste it here :)

I discovered something there:
```
    from .npm_client_handler import NpmClientHandler
  File "/home/predrag/.config/sublime-text/Packages/lsp_utils/st3/lsp_utils/npm_client_handler.py", line 3, in <module>
    from LSP.plugin.core.handlers import LanguageHandler
ImportError: No module named 'LSP.plugin.core.handlers'
```
just to see if you are experiencing the same thing :)

**Comment by predragnikolic** [comment]
Hello, 

> Do I have to install language servers even after installing this.

No. You don't need to install the language server. The plugin will install it for you.

Just to make sure, you followed this [readme](https://github.com/sublimelsp/LSP-typescript#lsp-typescript), right?

Lets debug this.
Can you open the `LSP.sublime-settings` 
and there enable logging by setting:
```
	"log_debug": true,
	"log_payloads": true,
```

Close sublime.
Open sublime, and open a `.js` or `.ts` file you opened before.
From the command palette run `LSP: toggle log panel`
copy the contents from it and paste it here. :)

I just tried installing LSP-typescript from Package control and it worked. Lets see why it doesn't work for you.

**Comment by lallenfrancisl** [comment]
It is completely blank !!!!

Here's my LSP settings
```
{
	"auto_show_diagnostics_panel": "never",
	"clients":
	{
		"pyls":
		{
			"command":
			[
				"~/.virtualenvs/pyls-virtual-env/bin/pyls"
			],
			"enabled": true,
			"languageId": "python",
			"scopes":
			[
				"source.python"
			],
			"settings":
			{
				"pyls":
				{
					"configurationSources":
					[
						"flake8"
					],
					"plugins":
					{
						"jedi_completion":
						{
							"enabled": true,
							"fuzzy": true,
							"include_params": true
						},
						"jedi_definition":
						{
							"enabled": true,
							"follow_builtin_imports": true,
							"follow_imports": true
						},
						"jedi_hover":
						{
							"enabled": true
						},
						"jedi_references":
						{
							"enabled": true
						},
						"jedi_signature_help":
						{
							"enabled": true
						},
						"jedi_symbols":
						{
							"enabled": true
						}
					}
				}
			},
			"syntaxes":
			[
				"Packages/Python/Python.sublime-syntax"
			]
		}
	},
	"show_diagnostics_count_in_view_status": true,
	"show_symbol_action_links": true,
	"log_debug": true,
	"log_payloads": true
}
```

**Comment by lallenfrancisl** [comment]
Ok I had to add `"log_stderr": true` too and got this

`:: --> lsp-typescript initialize(1): {'initializationOptions': {}, 'processId': 12069, 'clientInfo': {'version': '0.10.1', 'name': 'Sublime Text LSP'}, 'workspaceFolders': None, 'rootPath': None, 'rootUri': None, 'capabilities': {'textDocument': {'synchronization': {'dynamicRegistration': True, 'willSave': True, 'didSave': True, 'willSaveWaitUntil': True}, 'references': {'dynamicRegistration': True}, 'colorProvider': {'dynamicRegistration': True}, 'publishDiagnostics': {'relatedInformation': True}, 'rangeFormatting': {'dynamicRegistration': True}, 'declaration': {'dynamicRegistration': True, 'linkSupport': True}, 'implementation': {'dynamicRegistration': True, 'linkSupport': True}, 'completion': {'dynamicRegistration': True, 'completionItemKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]}, 'completionItem': {'snippetSupport': True}}, 'codeAction': {'dynamicRegistration': True, 'codeActionLiteralSupport': {'codeActionKind': {'valueSet': []}}}, 'signatureHelp': {'dynamicRegistration': True, 'signatureInformation': {'documentationFormat': ['markdown', 'plaintext'], 'parameterInformation': {'labelOffsetSupport': True}}}, 'typeDefinition': {'dynamicRegistration': True, 'linkSupport': True}, 'documentHighlight': {'dynamicRegistration': True}, 'hover': {'dynamicRegistration': True, 'contentFormat': ['markdown', 'plaintext']}, 'definition': {'dynamicRegistration': True, 'linkSupport': True}, 'formatting': {'dynamicRegistration': True}, 'documentSymbol': {'dynamicRegistration': True, 'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, 'rename': {'dynamicRegistration': True}}, 'experimental': {}, 'workspace': {'configuration': True, 'executeCommand': {}, 'symbol': {'dynamicRegistration': True, 'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, 'applyEdit': True, 'workspaceFolders': True, 'didChangeConfiguration': {'dynamicRegistration': True}, 'workspaceEdit': {'failureHandling': 'abort', 'documentChanges': True}}, 'window': {'workDoneProgress': True}}}
`

`:: <<< lsp-typescript 1: {'message': 'Request initialize failed with message: The "path" argument must be one of type string, Buffer, or URL. Received type object', 'code': -32603}
`

`:: <<< lsp-typescript 1: {'message': 'Request initialize failed with message: The "path" argument must be one of type string, Buffer, or URL. Received type object', 'code': -32603}
`

`:: <<< lsp-typescript 2: None
`
`::  -> lsp-typescript exit: None
`

**Comment by rwols** [comment]
Try opening a folder, not a single file.

**Comment by lallenfrancisl** [comment]
Oh it's working now. Isn't that a bug ?

**Comment by rwols** [comment]
It's not a bug. SublimeText can work in single-file mode, but some language servers don't like that. The typescript language server is "project"-based, it needs a tsconfig.json etc, it doesn't know what to do with a single file in a vacuum.

What we can do is display the error response in a dialog box from the initialize request. It is a bit vague now when an error response is returned.

**Comment by lallenfrancisl** [comment]
But the folder I opened also did not have a tsconfig.json. Is there someway of providing a default tsconfig or somthing like that to circumvent this.

**Comment by ykqmain** [comment]
@rwols 
Excuse me, Can LSP-typescript work in single file mode at present?
