### ISSUE TITLE
LSP-typescript reports 'No such file or directory' on Log Panel

### ISSUE THREAD

**Issue by patineboot** [sublimelsp/LSP-typescript#153]
Hello LSP-typescript,

LSP-typescript reports "No such file or directory" on Log Panel of Sublime Text.

I want to solve the LSP-typescript's "No such file or directory."
I assigned '_/usr/local/bin/npm_'  to npmLocation on the LSP-typescript settings as the following.
But, LSP-typescript still reports "No such file or directory" on the Log Panel.

Log Panel:
```bash
LSP-eslint: ESLint server running in node v18.4.0
LSP-typescript: [tsserver] /bin/sh: /usr/local/Cellar/node/18.4.0/bin/npm: No such file or directory
```

`npm` path: 
```bash
% which npm
/usr/local/bin/npm
```

LSP-typescript settings:
```bash
"npmLocation": "/usr/local/bin/npm",
```

**Comment by rchl** [comment]
The settings you specify have to follow the same structure as the defaults you see on the left when opening LSP-typescript settings. `npmLocation` needs to be nested inside `initializationOptions`.

**Comment by patineboot** [comment]
Thanks, @rchl.

I solved it.
LSP-typescript now reports "using npm from /usr/local/bin/npm."
