### ISSUE TITLE
How to setup the typescript-styled-plugin

### ISSUE THREAD

**Issue by predragnikolic** [sublimelsp/LSP-typescript#160]
This is a guide on how to setup the typescript-styled-plugin.

The best is to follow the installation instructions on https://github.com/microsoft/typescript-styled-plugin.

-----

1. In terminal run:
```
npm install --save-dev typescript-styled-plugin typescript
npm install --save styled-components  
npm i --save-dev @types/styled-components
```

2. The tsconfig.json file should include this plugin:
```
{
  "compilerOptions": {
    "plugins": [
      {
        "name": "typescript-styled-plugin",
        "tags": [
          "styled",
          "mytag"
        ]
      }
    ]
  }
}
```

3. Optionally configure the tags array. 

Create a index.ts file:
```
import styled from 'styled-components'

styled.button`
    color: blue;
    background: red; 
`
```
And that is it.
![2022-09-04-134230_1920x1200_scrot](https://user-images.githubusercontent.com/22029477/188312166-2e327e3f-02d7-47fb-857a-4210e9d94816.png)

[example.zip](https://github.com/sublimelsp/LSP-typescript/files/9484612/example.zip)

**Comment by rchl** [comment]
I wonder if we should enable and put it in Wiki or Discussions.
