### ISSUE TITLE
Listing and renaming private class methods omits hash sign

### ISSUE THREAD

**Issue by tukusejssirs** [sublimelsp/LSP-typescript#178]
When using [private class members and classes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields), LSP and/or LSP-typescript omit hash sign.

When I rename a private class method, the class sign is not in the text box. When I simply rename the method without adding a leading hash sign, the hash sign is removed from the method and thus made public. When I rename the method to a name that includes a leading hash sign, it is renamed correctly as expected. I would expect to place a hash sign into the text box, but select only the rest of the method name.

When I list all methods (etc) using `Goto Symbol`, it lists all methods without hash sign. I’d expect to list all private methods with a hash sign, as it is required when the function is referenced and/or called.

**Comment by rchl** [comment]
To make experience better https://github.com/typescript-language-server/typescript-language-server needs to support [prepareRename request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_prepareRename) but also LSP needs some fixes as it doesn't seem to implement that correctly.

Implementing support for `prepareRename` in https://github.com/typescript-language-server/typescript-language-server/pull/628

**Comment by tukusejssirs** [comment]
Thanks, @rchl, for your reply, explanation and for the quick PR! :pray:

**Comment by rchl** [comment]
Fixing LSP in https://github.com/sublimelsp/LSP/pull/2127.

**Comment by rchl** [comment]
New version of LSP with fixed support for prepareRename is now released.

**Comment by tukusejssirs** [comment]
Thanks, @rchl, it works perfectly! :pray:
