### ISSUE TITLE
Goto Type Definition?

### ISSUE THREAD

**Issue by Cobertos** [sublimelsp/LSP-typescript#179]
One thing I used to do a lot in `Typescript-Sublime-Plugin` was "Goto Type Definition". You could take the type of the current symbol, and go to the source of it. It was really nice for figuring out which properties were on the objects you're working with and generally just exploring/learning a library.

Is this a supported feature? Could it be added if not?

**Comment by Cobertos** [comment]
Oh, it seems the correct way is to right click and do `LSP > Goto Type Definition`. I've always just used the command palette so never realized there were different things in the right click menu.

Is this expected?

**Comment by rchl** [comment]
That's a bug in LSP that some items are missing there.

**Comment by rchl** [comment]
https://github.com/sublimelsp/LSP/issues/2130
