### ISSUE TITLE
Enable JavaScript autocomplete in HTML file

### ISSUE THREAD

**Issue by lzaaldian** [sublimelsp/LSP-typescript#18]
Hello,

I'm having hard time to make this work on HTML files.

What I have done is adding this code in user settings file

```
...
{
	"languageId": "html",
	"scopes": [
		"text.html.basic",
	],
	"syntaxes": [
		"Packages/Babel/JavaScript (Babel).sublime-syntax",
	],
},
...
```

Can anybody share how to properly enable JavaScript autocomplete features in HTML file?

**Comment by rchl** [comment]
I don't think this server supports Javascript embedded in HTML but I think https://github.com/sublimelsp/LSP-html does.

**Comment by lzaaldian** [comment]
Yes, you are correct. After installing `LSP-html`, the autocomplete for JavaScript works in HTML file 🎉. No additional configuration needed 🤘.

Thank you for your guidance.
