### ISSUE TITLE
Can crash on comment alignment

### ISSUE THREAD

**Issue by brian6932** [sublimelsp/LSP-typescript#198]
https://i.alienpls.org/tmV.apng

**Comment by rchl** [comment]
Is it really related to this package or it also happens with it disabled?

In any case, if it's related to this package then provide some details. Ideally a repo that reproduces, relevant configuration...

**Comment by brian6932** [comment]
> Is it really related to this package or it also happens with it disabled?

Only when it's enabled, seems like it only happens on a large amount of multi-line commenting

> In any case, if it's related to this package then provide some details. Ideally a repo that reproduces, relevant configuration...

Sublime Build 4147
LSP v1.22.0
LSP-typescript v2.2.0

<details>
  <summary>LSP.sublime-settings</summary>

```json
{
	"lsp_format_on_save": true,
	"lsp_code_actions_on_save": {
		"source.fixAll": true
	},
	"show_symbol_action_links": true,
	"inhibit_snippet_completions": true,
	"inhibit_word_completions": true,
	"show_inlay_hints": true
}
```

</details>


<details>
  <summary>LSP.typescript.sublime-settings</summary>

```json
{
	"settings": {
		"javascript.format.semicolons": "remove"
	}
}
```

</details>

**Comment by rchl** [comment]
Did you trigger file save just before it happened?

In any case, try in [safe mode](https://www.sublimetext.com/docs/safe_mode.html) with just LSP and LSP-typescript installed. I'm doubtful that this package alone can trigger such issue.

**Comment by brian6932** [comment]
> Did you trigger file save just before it happened?

yes


> In any case, try in [safe mode](https://www.sublimetext.com/docs/safe_mode.html) with just LSP and LSP-typescript installed. I'm doubtful that this package alone can trigger such issue.

It doesn't seem like the formatter is working for me in safe mode for whatever reason, I did migrate the configs. I'll look into this when I have more time.

**Comment by rchl** [comment]
I think it might be a conflict with some other package you have installed.

**Comment by rchl** [comment]
Close due to lack of reproduction. We can re-open if you have some reproducible case.
