### ISSUE TITLE
see all typescript warnings in one place?

### ISSUE THREAD

**Issue by gregsadetsky** [sublimelsp/LSP-typescript#204]
thank you for the amazingly useful package!

is there a way to see all typescript warnings for a file - or project/directory - in a single place? i.e. run a command to see them a bit like the "Find in Files..." results i.e. in a single view with the line + the warning + the line number?

thanks again

**Comment by predragnikolic** [comment]
Hello.

Yes, you can toggle the diagnostic panel.
See: https://lsp.sublimetext.io/keyboard_shortcuts/

**Comment by predragnikolic** [comment]
Also to note, 
the language server doesn't support project wide diagnostics at the moment.

There is this open issue https://github.com/typescript-language-server/typescript-language-server/issues/358

You can subscribe to that issue, if you want to track it.

**Comment by rwols** [comment]
You could also run `npm start` and inspect that for global errors, or use whatever build system you use.

**Comment by gregsadetsky** [comment]
amazing, the diagnostic panel is exactly what I was looking for. thanks!
