### ISSUE TITLE
automatic save format issue

### ISSUE THREAD

**Issue by h-polaris** [sublimelsp/LSP-typescript#209]
## lsp-typescript set automatic save to add semicolons, but it does not take effect on the last or only one line of the file.

**Comment by rchl** [comment]
Be more specific. I'm not sure what are you exactly doing on save.
I'm not sure if LSP-typescript has anything to do with fixing semicolons.

**Comment by h-polaris** [comment]
here are my lsp-typescript settings
```json
{
    "settings": {
        "javascript.format.semicolons": "insert",
        "typescript.format.semicolons": "insert"
    }
}
```
I want to automatically format the code as I save to add a semicolon at the end of each line.

example:
```js
// right
var a = 1;
var b = 2;
```

but the results are not what I expected.
The result is this:
```js
// wrong
var a = 1;
var b = 2 // The last line does not append a semicolon
```

or:
```js
var a = 1 // No semicolons are appended when there is only one line
```

What changes do I need to set?

**Comment by rchl** [comment]
And do you expect that to be fixed on running "LSP: Format file" or did you set up some `lsp_code_actions_on_save` for this?

**Comment by rchl** [comment]
Fixed in https://github.com/sublimelsp/LSP-typescript/releases/tag/v2.4.0
