### ISSUE TITLE
Inline hints do not show

### ISSUE THREAD

**Issue by beautifulcoder** [sublimelsp/LSP-typescript#211]
Wondering if anyone has been able to get the inline hints to work successfully for TypeScript/JavaScript files in Sublime Text 4. I installed both the LSP and LSP-typescript packages, installed TypeScript via NPM globally, enabled inline hints in the settings. So far, nothing works. All other functionality seems to work correctly, am I doing something wrong? I am on the latest TypeScript 5.0.4.

![Screenshot 2023-04-30 113835](https://user-images.githubusercontent.com/5228509/235365164-1a421b28-ee42-4a3f-ba83-6f988f7a6bc0.png)

LSP.sublime-settings

```json
{
  "show_inlay_hints": true,
}
```

LSP-typescript.sublime-settings

```json
{
    "javascript.inlayHints.includeInlayEnumMemberValueHints": false,
    "javascript.inlayHints.includeInlayFunctionLikeReturnTypeHints": true,
    "javascript.inlayHints.includeInlayFunctionParameterTypeHints": true,
    "javascript.inlayHints.includeInlayParameterNameHints": "all", // none | literals | all
    "javascript.inlayHints.includeInlayParameterNameHintsWhenArgumentMatchesName": false,
    "javascript.inlayHints.includeInlayPropertyDeclarationTypeHints": true,
    "javascript.inlayHints.includeInlayVariableTypeHints": true,
    "javascript.inlayHints.includeInlayVariableTypeHintsWhenTypeMatchesName": false,
    "typescript.inlayHints.includeInlayEnumMemberValueHints": false,
    "typescript.inlayHints.includeInlayFunctionLikeReturnTypeHints": true,
    "typescript.inlayHints.includeInlayFunctionParameterTypeHints": true,
    "typescript.inlayHints.includeInlayParameterNameHints": "all", // none | literals | all
    "typescript.inlayHints.includeInlayParameterNameHintsWhenArgumentMatchesName": false,
    "typescript.inlayHints.includeInlayPropertyDeclarationTypeHints": true,
    "typescript.inlayHints.includeInlayVariableTypeHints": true,
    "typescript.inlayHints.includeInlayVariableTypeHintsWhenTypeMatchesName": false,
}
```

**Comment by rwols** [comment]
What other packages do you have installed?

**Comment by predragnikolic** [comment]
Your LSP-typescript.sublime-settings file doesn't look correct. 

Install LSP-json and it will give you the error. 🙂

All those server settings you specified need to nested in a "settings" object.
```
// LSP-typescript.sublime-settings
{
   "settings" { ...paste your inlay hint settings }
}
```

**Comment by rchl** [comment]
> Install LSP-json and it will give you the error. 🙂

LSP-json doesn't report unknown top-level settings in LSP-* settings.

**Comment by beautifulcoder** [comment]
Holy cow, thank you @predragnikolic, nesting my settings under `settings` does the trick! I will share this with the rest of the Sublime community in case anyone else stumbles on this.
