### ISSUE TITLE
Full type definition

### ISSUE THREAD

**Issue by dportalesr** [sublimelsp/LSP-typescript#213]
When inspecting a type with a long definition, the tooltip triggered by hovering shows basically only a preview of it.

![LSP-typescript 🔊-20230518-000603](https://github.com/sublimelsp/LSP-typescript/assets/237597/196ff83e-e5fa-409d-a281-58dd04ea75b9)

In my case, "Go to type definition" is not very helpful since my type is an union of other unions which definitions could reside in multiple files. 

Is there a way to enable or get (even using other method) the full details of the resolved type? That is, showing the whole list of fields instead of showing "..." or "... n more..."

Thanks in advance!

**Comment by rchl** [comment]
Maybe try with https://www.typescriptlang.org/tsconfig#noErrorTruncation enabled in `tsconfig.json`.

Note that I've seen reports of this option making type checking a lot slower so probably best to only use it when debugging.

**Comment by dportalesr** [comment]
Unfortunately, that didn't work. I also tried with both `tsserver.logVerbosity` and `tsserver.trace` but no luck whatsoever.

**Comment by rchl** [comment]
Can you provide code sample or project that reproduces?

Note that this is not something that this server would have to support anyway. It's all coming from TypeScript itself. Personally I've used this snippet before that I found on StackOverflow somewhere: https://gist.github.com/rchl/9ca0a2bdc95f2c36c4d590572a4d038c (you'd need to modify the code of the type of course).

**Comment by dportalesr** [comment]
Related:
https://github.com/microsoft/TypeScript/issues/38557
https://github.com/microsoft/TypeScript/issues/26238

Closing this since, as you've said, it's a TS compiler thing. Thanks!
