### ISSUE TITLE
Only absolute/relative auto-import

### ISSUE THREAD

**Issue by deger4beger** [sublimelsp/LSP-typescript#232]
I need to always use absolute imports in my current project, found this option in `Preferences: LSP-typescript Settings`, by default it specifies the shortest path:

`"importModuleSpecifierPreference": "shortest", `

Tried to set `"absolute"` value but it's not working and there is no docs with possible values

**Comment by rchl** [comment]
If you install LSP-json then you'll get suggestions with available values.

**Comment by deger4beger** [comment]
@rchl thanks !

**Comment by sricks** [comment]
Sorry to bother, but this isn't working for me; lsp-typescript insists on using relative import paths.

This is my LSP-typescript.sublime-settings:
```
// Settings in here override those in "LSP-typescript/LSP-typescript.sublime-settings"
{
	"schemes": ["file"],

	"initializationOptions": {
		"preferences": {
			"importModuleSpecifierPreference": "relative",
		},
	},
}
``` 

LSP-json confirms that these are valid values, I've restarted everything, and aliased imports are configured correctly. My tsconfig.json looks like this:

```
{
	"compilerOptions": {
		"baseUrl": ".",
		"paths": { "@/*": ["src/*"], "@components/*": ["src/components/*"] },
...
```

**Comment by sricks** [comment]
:facepalm: It was supposed to be `non-relative` for the behavior I wanted. Confirming this works in LSP-typescript.sublime-settings:

```
// Settings in here override those in "LSP-typescript/LSP-typescript.sublime-settings"

{
	"schemes": ["file"],

	"initializationOptions": {
		"preferences": {
			"importModuleSpecifierPreference": "non-relative",
		},
	},
	"diagnostics_mode": "workspace",
}
```
