### ISSUE TITLE
Infer parameter types from usage

### ISSUE THREAD

**Issue by mikez** [sublimelsp/LSP-typescript#233]
Is there a way to trigger "Infer parameter types from usage" on request?

Currently, I do it by toggling the diagnostic panel (⌥⌘M), seeking the file and line I'm on, and then double-clicking the line where it says "Infer parameter types from usage".

Is there an easier way?

(Thank you for this plugin, @rchl.)

**Comment by mikez** [comment]
@rchl Thank you, I just tried it out. It doesn't show the "infer parameters from usage".

The diagnostics panel shows this:
![image](https://github.com/sublimelsp/LSP-typescript/assets/216956/59265b32-6701-4e07-ae6a-913c87fdd466)

Pressing `⌘+.` while on line 21 in said file only shows this one action:
![image](https://github.com/sublimelsp/LSP-typescript/assets/216956/03e4605f-cc1e-43c8-9956-4cce59b599b7)

How can I make "infer parameters from usage" an option as well?

**Comment by rchl** [comment]
I think it might show if you place your cursor within parameters since those code actions are context-specific.

**Comment by predrag-codetribe** [comment]
Here is how it works for me
https://github.com/sublimelsp/LSP-typescript/assets/115091796/607d2167-9b70-45b4-9372-e582bfebf427

**Comment by mikez** [comment]
@rchl That resolved it! Thank you. :)

Here's my updated flow:

1. Move cursor to the first function parameter.
2. Press `⌘+.` & `↵`

Follow-up question: Can I cycle through all lines that appear in ⌥⌘M, as opposed to having to click on each? A "find next" diagnostic action, a bit like the ⌘G key for search.

**Comment by rchl** [comment]
You can find various related key bindings in `Preferences: LSP key bindings` including ones that show diagnostics in a quick panel and ones that jump to next/previous diagnostics. This is a better way of handling navigation than using the panel since the latter is erratic.

**Comment by mikez** [comment]
@rchl 👌. `…/LSP/Default.sublime-keymap` is an amazing resource. Thank you!!

**Comment by predrag-codetribe** [comment]
@mikez I use [Kap](https://getkap.co/) . It allows me to export a video to mp4, gif.
