### ISSUE TITLE
Type checking works different from other IDEs

### ISSUE THREAD

**Issue by moonlitgrace** [sublimelsp/LSP-typescript#250]
For exmaple let's take this:
```ts
createEffect(() => {
  if (!dotLottie()) return;
  dotLottie().addEventListener('play', console.log);
  dotLottie().addEventListener('freeze', console.log);
});
```
looks good right? but it shows this error even after guard clause check
![2024-06-07_14-41](https://github.com/sublimelsp/LSP-typescript/assets/114811070/a9a0b163-2e15-4375-8790-328cf774a35c)

but on vscode it works fine:
![2024-06-07_14-42](https://github.com/sublimelsp/LSP-typescript/assets/114811070/23844ef0-3623-4cae-ae7f-7cedff05a306)

```Using LSP-Typescript version: 5.0.4```

**Comment by rchl** [comment]
The difference could be that vscode uses different version of typescript. In vscode you can switch which version of TS is used from the status field.

**Comment by moonlitgrace** [comment]
@rchl thank you for your response.
yea but something else is problem, but its good now.
closing this... thanks again :)
