### ISSUE TITLE
errors not displayed in js files

### ISSUE THREAD

**Issue by PierBover** [sublimelsp/LSP-typescript#258]
Not sure if this is an issue with `LSP-typescript` but errors are not show in `.js` files.

This is an undefined variable:

<img width="600" alt="image" src="https://github.com/user-attachments/assets/07b7fca3-5146-47a5-9ab8-ff7aa15c3096">

You can see the LSP is running as there is the blue dotted line for the unused variable.

I though it was a config error but as soon as I change the extension from `.js` to `.ts` it works as expected:

<img width="560" alt="image" src="https://github.com/user-attachments/assets/916e7307-aeff-4b15-8ad0-d569b3ba0343">

**Comment by predragnikolic** [comment]
That is expected. 
You need to enable `checkJs` in tsconfig.json or use the `// @ts-check` comment. 

https://www.typescriptlang.org/tsconfig/#checkJs

**Comment by PierBover** [comment]
thanks @predragnikolic
