### ISSUE TITLE
Do not start when there is no tsconfig.json

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP-typescript#26]
You can use the `can_start` classmethod for this from AbstractPlugin.

**Comment by rchl** [comment]
What's the problem with starting it regardless of whether config is present?

It still provides some intelligence (completions), even without the config since it uses default options then.

BTW. There is also `jsconfig.json` (https://www.typescriptlang.org/docs/handbook/tsconfig-json.html)

**Comment by predragnikolic** [comment]
We should definitely start the server regardless if the tsconfig or jsconfig file is pressent, as those files exist to allow a user to change the default ts language server settings. 

Those files are not mandatory to start the server, so no need to stop the server from initializing if they are not present.

**Comment by rwols** [comment]
Thanks, these are all good points.
