### ISSUE TITLE
Crash on startup with status code -32603

### ISSUE THREAD

**Issue by ephemer** [sublimelsp/LSP-typescript#29]
More often than not, when I start Sublime Text (I am on build 4090) and open a typescript file I get the following message:

```
LSP-typescript exited with status code -32603 and message:

---
Request initialize failed with message: The "path" argument must be of type string or an instance of Buffer or URL. Received null
---

Do you want to restart LSP-typescript?

If you choose Cancel, LSP-typescript will be disabled for this window until you restart Sublime Text.
```

If I press restart then the same message appears (and so on).

The solution appears to be closing Sublime Text entirely and then navigating to the file again (maybe after a short delay). I'm not sure if this is an issue with the LSP plugin or LSP-Typescript itself (this is the only plugin I'm using that hooks into Sublime LSP)

**Comment by rchl** [comment]
That's an issue with LSP https://github.com/sublimelsp/LSP/issues/1374

**Comment by predragnikolic** [comment]
Fixed with https://github.com/sublimelsp/LSP/pull/1395

**Comment by rwols** [comment]
Not really. If you open a new window and then open a single file from that window, the server will complain about “invalid” workspace folders.

**Comment by rchl** [comment]
But that's just pure "bug" of the typescript LS since it doesn't support folder-less workspaces.

We would keep it open for tracking but there is nothing we can or should do probably.

**Comment by rwols** [comment]
True, I suppose this can be closed because it’s fixed “on our end” :)

**Comment by rwols** [comment]
Well, I still say LSP-typescript should use can_start and work around it that way.

**Comment by rchl** [comment]
Fixed in https://github.com/sublimelsp/LSP-typescript/releases/tag/1.1.3
