### ISSUE TITLE
Tag a new release for the Cache directory change

### ISSUE THREAD

**Issue by jfcherng** [sublimelsp/LSP-typescript#32]
Could we have a new release for https://github.com/sublimelsp/LSP-typescript/commit/6ffdd0a36bb097ab8ab5fb3a33b31bf4781ed48f since I don't think neither the server nor this client will have other update, at least in the near future.

Not sure about LSP-eslint. It's still installed in the Cache dir for the current release.

**Comment by rchl** [comment]
Will do.

BTW. typescript language server will hopefully pick up some speed, hopefully as there is a maintaner now. :)

**Comment by jfcherng** [comment]
> BTW. typescript language server will hopefully pick up some speed, hopefully as there is a maintaner now. :)

Oh, that's a good news!
