### ISSUE TITLE
Go to symbol definition error: maximum call stack size exceeded

### ISSUE THREAD

**Issue by srgcdev** [sublimelsp/LSP-typescript#35]
Hi,

Using lsp-typescript in an angular project, when I want to go to symbol definition for some clasess in node_modules, angular clases or whatever library, I have this error:
```
Request textDocument/definition failed with message: Error processing request. Maximum call stack size exceeded
```
Any ideas?

**Comment by rchl** [comment]
No idea without a reproduction repo. But it's likely a problem in https://github.com/theia-ide/typescript-language-server or typescript itself.

**Comment by rchl** [comment]
Don't have enough info to reproduce so closing it but if you have a way to reproduce you should report it in theia project.
