### ISSUE TITLE
Organize Imports

### ISSUE THREAD

**Issue by mauroreisvieira** [sublimelsp/LSP-typescript#41]
It's possible to add that feature in LSP-typescript?

https://user-images.githubusercontent.com/3084774/107800644-efa33e00-6d56-11eb-8e2f-2ebfcc933a36.mp4

Actual behavior we need to go to the unused import.
right click on `choose code action` > `Remove unused...`

<img width="895" alt="Screenshot 2021-02-12 at 17 25 55" src="https://user-images.githubusercontent.com/3084774/107801213-b4edd580-6d57-11eb-92f2-49c07e57bc1c.png">

**Comment by rchl** [comment]
Added the `LSP-typescript: Organize Imports` command to the Command Palette.

You can also create a key binding if you want. See https://github.com/sublimelsp/LSP-typescript#organize-imports-command

**Comment by predragnikolic** [comment]
Because we released a new version for LSP-typescript, will we now release a new version for LSP?

**Comment by rchl** [comment]
I guess I have rushed a bit here but I don't think it's a big deal if this command won't work until LSP is released. It also won't work at all in ST3...

**Comment by mauroreisvieira** [comment]
Ok, so that key binding or `LSP-typescript: Organize Imports` will only work on the next LSP release, right?

**Comment by predragnikolic** [comment]
Yes, that is correct
