### ISSUE TITLE
A question about folder in the current workspace

### ISSUE THREAD

**Issue by john-cj** [sublimelsp/LSP-typescript#49]
When I open a file without opening a directory, I see the following message in the Sublime Text's console:

```
LSP-typescript: This server only works when the window workspace includes some folders!
```

Does it mean that a folder is required by LSP-typescript **package**? Or does it mean that it is required by the `lsp-typescript` **server** (which is actually one of the options of the [LSP](https://github.com/sublimelsp/LSP) package)? Cheers.

**Comment by rwols** [comment]
It is required by https://github.com/theia-ide/typescript-language-server, which is the actual underlying language server.

**Comment by john-cj** [comment]
@rwols Since I'm beginner, some things are very confusing.

As far as I understand, there are basically two ways to get LSP to work. The first:

1. Install LSP.
2. Install LSP-typescript.
3. In LSP settings, enable the `lsp-typescript` server.

The second:

1. `npm install --save typescript`
2. `npm install -g typescript-language-server`
3. Install LSP. There is no need to install LSP-typescript alongside.
4. In LSP settings, enable the `typescript-language-server` server.

And so it seems to me that `typescript-language-server` (aka Theia TypeScript Language Server) is actually don't need the LSP-typescript. But at the same time the LSP-typescript's README says that the package _do_ works through Theia TypeScript Language Server. Could you explain this if you have a minute?

**Comment by rchl** [comment]
> As far as I understand, there are basically two ways to get LSP to work. The first:
> 
> 1. Install LSP.
> 2. Install LSP-typescript.
> 3. In LSP settings, enable `lsp-typescript`.

There is no need for point 3 in this case. Everything is enabled once you install the packages.

> The second:
> 
> 1. `npm install --save typescript`
> 2. `npm install -g typescript-language-server`
> 3. Install LSP. There is no need to install LSP-typescript alongside.
> 4. In LSP settings, enable `typescript-language-server`.

That's an option too. At least in ST4. In ST4 version the configuration for typescript was removed since it's assumed and preferred that the user uses LSP-typescript instead. To be fair it's also recommended for ST3.

> And so it seems to me that `typescript-language-server` (aka Theia TypeScript Language Server) is actually don't need the LSP-typescript.

LSP-typescript is a helper package and its (and other helper packages's) purpose is to:
 - install and manage the server (in this case Theia) for the user thus simplifying the configuration and the setup process
 - provide a settings schema (optionally) so that you get settings validation and auto-completions when opening (in this case) `LPS-typescript.sublime-settings` (this requires `LSP-json` being installed also).
 - in some cases implement some additional functionality that complements the server and is not possible to provide without a helper package. In the case of Theia, the helper package implements some functionality needed for the "LSP: Rename" option.

**Comment by rwols** [comment]
> Could you explain this if you have a minute?

Sure. Apologies that the documentation is unclear on this.

There are two ways to set up a language server:

1. Set it up yourself with just some JSON configuration. You have to manage updating the server binary/files yourself, and you won't be able to "tune" certain functionality. You will have to figure out the initializationOptions and server settings yourself. You do this by editing the file Packages/User/LSP.sublime-settings and modifying the `"clients"` object inside of that file. Run the command `Preferences: LSP Settings` from the Command Palette to inspect and/or edit that file.
2. You can write a "helper package". Such a helper package defines a file in the form of LSP-*.sublime-settings, where `*` is any identifier. Furthermore, it may define additional Python code to fine-tune the integration with Sublime Text. In practice, some servers need this fine-tuning (or: "glue code"). Furthermore, a helper package may additionally install the server binary in the background, freeing you from managing that yourself. The ST package LSP-typescript does all of this.

While it is true that you can run https://github.com/theia-ide/typescript-language-server manually, I would always suggest to install a helper package.

The situation you're in now is that you have both option (1) and option (2) enabled. So you're running two versions of the same server in the background. What I would suggest is to do the following:

1. Disable your `lsp-typescript` configuration by running `Preferences: LSP Settings` from the Command Palette, and setting `"enabled": false` in the right-most view for the `lsp-typescript` entry in your `"clients"` json object.
2. If instead you enabled the `lsp-typescript` configuration in your project, run `LSP: Disable Language Server In Project` and choose `lsp-typescript`.
3. Remove the server deployment files that you installed manually: `npm -g remove typescript-language-server` in the terminal.

I reckon you're using ST3 as you're talking about `lsp-typescript`. In ST4, this "default configuration" is removed to remove the confusion.

**Comment by john-cj** [comment]
Thanks a lot. Very fast and very detailed explanations.

> In the ST4 version, the configuration for **typescript** was removed since it's assumed and preferred that the user uses LSP-typescript instead. To be fair it's also recommended for ST3.

Since I wasn't completely sure what @rchl assumed by "typescript", I installed ST4 and now I see that he assumed `typescript-language-server`. So in ST4 the only LSP configuration for JavaScript and TypeScript is `lsp-typescript`. And so the preferred way to use LSP in ST3 and the only to use it in ST4 is what I called "the first way". (This is just a reminder for my reference. And a clarification for other people like me who might visit this issue.)

**Comment by john-cj** [comment]
@rwols Could you explain why you suggest to disable the `lsp-typescript` configuration?

If I follow these steps:

1. Create a new Sublime Text profile
2. Install LSP
3. Install LSP-typescript

... LSP works and the LSP configuration file is empty.

But if I paste the following content there, as per your suggestion (if I understood it correctly)

```
{
  "clients":
  {
    "lsp-typescript":
    {
      "enabled": false
    }
  }
}
```

... LSP stops working.

(Yes, I use Sublime Text 3. However I just installed Sublime Text side-by-side.)

**Comment by rchl** [comment]
He meant to just remove that configuration, not set enable to false.

**Comment by john-cj** [comment]
@rchl Hmm, maybe, but the recommendation seems to be very clear:

> Disable your `lsp-typescript` configuration by running `Preferences: LSP Settings` from the Command Palette, and setting `"enabled": false` in the right-most view for the `lsp-typescript` entry in your `"clients"` json object.

**Comment by rchl** [comment]
I think it was a typo on @rwols part. ST3 includes those configurations that are related to typescript:
 - lsp-tsserver
 - javascript-typescript-langserver
 - typescript-language-server

So I think he meant to disable those.

BTW. Those configurations are included by default in bundled `LSP.sublime-settings` (you'll find them at the bottom of that file). Those are disabled by default so to enable them you have to include that short snippet in your `LSP.sublime-settings` with `"enabled":  true`. So if you don't want them to be enabled you can either remove your override completely or set `"enabled" false`.

**Comment by rwols** [comment]
Yes, I totally screwed up there. I meant disable those configurations mentioned by @rchl.
