### ISSUE TITLE
 not list installed package when type import on macOS

### ISSUE THREAD

**Issue by loricheung** [sublimelsp/LSP-typescript#54]
I reinstall many times, it didn't work anyway. but this function works on my windows.

### on macOS
<img width="347" alt="Screen Shot 2021-05-02 at 1 07 51 PM" src="https://user-images.githubusercontent.com/8928155/116802818-adfd8480-ab48-11eb-86ba-b557bf5ef74c.png">

### on windows
![{BCA852FD-BD00-4670-AEED-A269C21E625C} png](https://user-images.githubusercontent.com/8928155/116803527-fc138780-ab4a-11eb-9865-42c554f283af.jpg)
![{83D43612-8BBC-4A3C-BF87-A512C485F9A6} png](https://user-images.githubusercontent.com/8928155/116803529-ffa70e80-ab4a-11eb-9ee5-1e1d4a795c5e.jpg)

### here is troubleshooting on macOS

[Troubleshooting.md](https://github.com/sublimelsp/LSP-typescript/files/6410816/Troubleshooting.md)

### and here is troubleshooting on windows
[troubleshooting on windows.md](https://github.com/sublimelsp/LSP-typescript/files/6410819/troubleshooting.on.windows.md)

**Comment by predragnikolic** [comment]
Hello,
Did you run `npm i` on Mac OS?

**Comment by rchl** [comment]
One thing that might be worth trying is using older NodeJS version (14 for example) since I can see that you are using version 16 on Mac.

You could try that easily by setting `"nodejs_runtime": ["local"],` in "LSP Utils settings" opened through Command Palette.

**Comment by loricheung** [comment]
> Hello,
> Did you run `npm i` on Mac OS?

Yes, actually I tried in same project folder, it also didn't work

**Comment by loricheung** [comment]
> One thing that might be worth trying is using older NodeJS version (14 for example) since I can see that you are using version 16 on Mac.
> 
> You could try that easily by setting `"nodejs_runtime": ["local"],` in "LSP Utils settings" opened through Command Palette.

Yeah! It works! 

Now I switch system node from 16.0.0 to 14.16.1, then change command to `"command": ["node", "${server_path}", "--stdio"]` in LSP-typescript settings, but sublime said it can't find node in path. I'm pretty sure that node can be found in path. what I missed?

**Comment by loricheung** [comment]
Now I doubt it not caused by node version, it's sublime es7 snippets issue. 

when I type `imp` and press enter, it will automatically type `import moduleName from 'module'`, the cursor will locate at `'module'` first, when I press tab, it will switch to `'moduleName'`, then I press tab, it will goto end of line. during these steps, it will not show anything. 

But after these steps, I move cursor to `'module'` manually, it will show all packages I already installed!

**Comment by rchl** [comment]
> Now I doubt it not caused by node version, it's sublime es7 snippets issue.

Which package are you talking about exactly?
It's possible that it suppresses other completions, I guess, but its code would need to be checked to confirm that.

**Comment by loricheung** [comment]
> > Now I doubt it not caused by node version, it's sublime es7 snippets issue.
> 
> Which package are you talking about exactly?
> It's possible that it suppresses other completions, I guess, but its code would need to be checked to confirm that.

I reinstall node 16.0.0 again,  type `import React from 'react'` by manually and I found it also works. 
<img width="429" alt="Screen Shot 2021-05-03 at 10 29 30 PM" src="https://user-images.githubusercontent.com/8928155/116889565-48e88280-ac5f-11eb-82c9-a57c42675843.png">

maybe it's not LSP-typescript's problem.
