### ISSUE TITLE
Can not autocomplete if attribute starts with "$"

### ISSUE THREAD

**Issue by jgburet** [sublimelsp/LSP-typescript#56]
https://user-images.githubusercontent.com/1304987/117413819-b70a9f00-af16-11eb-9506-24ebee014ac8.mov

<img width="603" alt="Screenshot 2021-05-07 at 09 33 02" src="https://user-images.githubusercontent.com/1304987/117414266-39935e80-af17-11eb-82bd-0c7576309f9a.png">

<img width="320" alt="Screenshot 2021-05-07 at 09 33 40" src="https://user-images.githubusercontent.com/1304987/117414350-50d24c00-af17-11eb-9d27-bc9f7f2e8323.png">

```typescript
import { firefox, FirefoxBrowser, Page } from 'playwright';

async function main(): Promise<void> {
    let browser: FirefoxBrowser;
    browser = await firefox.launch({ headless: false, slowMo: 300 });
    const page = await browser.newPage();

    await page.$$ // pressing `tab` | `enter` will remove the characters of the attribute name after the `.`
}

```

**Comment by rchl** [comment]
https://github.com/sublimelsp/LSP/issues/1088
