### ISSUE TITLE
Completion error

### ISSUE THREAD

**Issue by elsassph** [sublimelsp/LSP-typescript#57]
System: Mac OS Mojave

LSP-json works fine, but for TS, when I edit the code I get in the status bar:
```
Completion error: Request textDocument/completion failed with message: Cannot write after the stream was destroyed (-32603)
```
I've tried installing both `LSP` and `LSP-typescript` from git instead of from Package Control but the error persists.

Server troubleshooter seem ok:
```
# Troubleshooting: LSP-typescript
## Version
 - LSP: 1.3.1
 - Sublime Text: 4107
## Server Test Run
 - exit code: 0
 - output
```

**Comment by rchl** [comment]
Could you try disabling and re-enabling the `LSP-typescript` package from the Command Palette?
Also restart ST for good measure (but not too fast since it might me re-installing the server after re-enabling - watch the status bar for progress).

**Comment by rchl** [comment]
Closing due to no response.
