### ISSUE TITLE
Using Flow in React Project. Type annotations can only be used in TypeScript files error.

### ISSUE THREAD

**Issue by bigkrp** [sublimelsp/LSP-typescript#60]
In my react\javascript project i use Flow, and often get this error:
``` error   Type annotations can only be used in TypeScript files. ​typescript:8010```

How can i disable it?

**Comment by rchl** [comment]
`LSP: Disable Language Server in Project` -> LSP-typescript

You don't want to run LSP-typescript in a flow project. You might want to use `LSP-flow` instead.
