### ISSUE TITLE
"Code action: Convert 'const' to 'let'" breaks in for statement

### ISSUE THREAD

**Issue by saneef** [sublimelsp/LSP-typescript#67]
The `const` to `let` conversion in for statement creates wrong code:

Before:
```js
for (const i: number = 0; i < 20; i++) {
    console.log(i);
}
```

After:
```js
letconst i: number = 0; i < 20; i++) {
    console.log(i);
}
```

![Wrong code action with for loop](https://user-images.githubusercontent.com/81863/122675456-24d50680-d1f7-11eb-80ea-ba87d8cc5912.gif)

**Comment by rchl** [comment]
This is an issue in the Typescript itself. You can reproduce it here also:

https://www.typescriptlang.org/play?#code/LAKAZg9gTgBAFAYwgOwM4BcYEsBcNkCuAtgEYCmsAvDAAwDc2MAPDAEz3YDUnAlDAN6gYwmEjQQANmQB0EiAHM4WHqAC+oIA

I'd suggest reporting that at https://github.com/microsoft/TypeScript/issues, if it's not already.
