### ISSUE TITLE
package name error

### ISSUE THREAD

**Issue by princemaple** [sublimelsp/LSP-typescript#75]
Seeing the 0.6.0 release of typescript-language-server, I tried to bump the version here.
I got this error. Wondering how it was first installed?

```
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "typescript-language-server" under a package
npm ERR! also called "typescript-language-server". Did you name your project the same      
npm ERR! as the dependency you're installing?
npm ERR! 
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>    
```

**Comment by rchl** [comment]
I've changed the value of `name` property to not match the dependency name and also kicked dependabot to get it to make a PR. So I hope all should be fine now.
