### ISSUE TITLE
Goto definition: error: Unable to open URI

### ISSUE THREAD

**Issue by unlight** [sublimelsp/LSP-typescript#78]
Subject. It is started few days ago.
Looks like it is related to "typescript-language-server": "0.6.0" or latest lsp typescript 1.3.0

I tried to rollback to previous 0.5.1, but it updates automatically without asking.

Also I noticed weird suggestion (when doing lsp goto definition), it should be: `{file}:{Line}`
![image](https://user-images.githubusercontent.com/301732/129479256-25ecd8a2-212a-4876-9b83-da14be4ccf14.png)

**Env**:
ST 4112
LSP typescript: 1.3.0
Windows 10
Node 14.17.5

**Comment by rwols** [comment]
Is the URI not a `file:` URI?

**Comment by unlight** [comment]
@rwols 
No, it starts from letter `C:/...`
![image](https://user-images.githubusercontent.com/301732/129480578-8a972c70-1232-4491-898a-645e95ef8a7d.png)

**Comment by rwols** [comment]
Can you show what the payload of the response to textDocument/definition is?

To see server payloads, put "log_server": ["panel"] in Packages/User/LSP.sublime-settings, then open the log panel by running LSP: Toggle Log Panel. Then re-do your steps to trigger the request.

**Comment by rwols** [comment]
If the server returns literal filepaths, then I think what happens is that we accidentally use `C:` as the URI scheme.

**Comment by unlight** [comment]
```
:: --> LSP-typescript textDocument/definition(35): {'textDocument': {'uri': 'file:///C:/Dev/project/xxx/workers/cancel_shipment.js'}, 'workDoneToken': 'wd35', 'position': {'line': 27, 'character': 20}}
:: <<< LSP-typescript 35: [{'uri': 'C:/Dev/project/xxx/lib/accounting/index.js', 'range': {'end': {'line': 4, 'character': 15}, 'start': {'line': 4, 'character': 8}}}, {'uri': 'C:/Dev/project/xxx/lib/accounting/combine.js', 'range': {'end': {'line': 146, 'character': 16}, 'start': {'line': 146, 'character': 9}}}]
```

**Comment by rwols** [comment]
Thanks. That doesn’t look like an URI to me in the server response. So it’s a server issue.

**Comment by rwols** [comment]
Open an issue here https://github.com/typescript-language-server/typescript-language-server/issues

**Comment by rchl** [comment]
Fixing in https://github.com/typescript-language-server/typescript-language-server/pull/249

**Comment by rchl** [comment]
Version v1.3.1 with the fix is now on package control.
