### ISSUE TITLE
No diagnostics showing at all

### ISSUE THREAD

**Issue by duydang2311** [sublimelsp/LSP-typescript#79]
Hello there, I open a ts file in my project, type some random words there to get some syntax errors but I don't see any diagnostics showing up to notify me about that.
It was working fine when I first installed it days ago through package control:
![image](https://user-images.githubusercontent.com/34796192/129487240-3d6d0203-4dcb-4d6b-9fe4-3baf96c58b36.png)
![image](https://user-images.githubusercontent.com/34796192/129487263-95657312-7b17-4592-8a91-604e1c05489a.png)

This is how it looks now (auto-completion still works):
![image](https://user-images.githubusercontent.com/34796192/129487593-76fbbdd3-b412-46c1-9df9-046268e6b50f.png)

I have tried to re-install several times but no difference, hope I can have some help!
Thank you, and here is the trouble-shooting:

# Troubleshooting: LSP-typescript
## Version
 - LSP: 1.8.0
 - Sublime Text: 4113
## Server Test Run
 - exit code: 0
 - output

## Server Configuration
 - command
```json
[
  "${node_bin}", 
  "${server_path}", 
  "--stdio"
]
```
 - shell command
```sh
"C:\Program Files\nodejs\node.EXE" "C:\Users\Duy Dang\AppData\Local\Sublime Text\Package Storage\LSP-typescript\14.15.3\typescript-language-server\node_modules\typescript-language-server\lib\cli.js" --stdio
```
 - selector
```
(source.jsx | source.js.react)|(source.js)|(source.tsx)|(source.ts)
```
 - priority_selector
```
(source.javascriptreact)|(source.javascript)|(source.typescriptreact)|(source.typescript)
```
 - init_options
```json
{
  "logVerbosity": "off", 
  "plugins": [], 
  "preferences": {
    "allowRenameOfImportPath": true, 
    "includeCompletionsForImportStatements": true, 
    "includeCompletionsForModuleExports": true, 
    "includeCompletionsWithInsertText": true
  }
}
```
 - settings
```json
{
  "javascript": {
    "suggest": {
      "completeFunctionCalls": true
    }
  }, 
  "typescript": {
    "suggest": {
      "completeFunctionCalls": true
    }
  }
}
```
 - env
```json
{
  "PATH": "C:\\Program Files\\nodejs;C:\\Program Files\\nodejs;"
}
```

## Active view
 - File name
```
./index.ts
```
 - Settings
```json
{
  "auto_complete_selector": "source - comment", 
  "lsp_active": true, 
  "syntax": "Packages/JavaScript/TypeScript.sublime-syntax"
}
```
 - base scope
```
source.ts
```

## Project / Workspace
 - folders
```json
[
  "sunday-altv/"
]
```
 - is project: False

## LSP configuration

```json
{
  "show_diagnostics_count_in_view_status": true, 
  "show_diagnostics_panel_on_save": 0, 
  "show_diagnostics_severity_level": 4
}
```

**Comment by rchl** [comment]
Can you set `"log_debug": true,` in `LSP.sublime-settings` and then reopen the file and check the sublime console.

**Comment by rchl** [comment]
It's looking like a regression in the new server version. Same as #78.

**Comment by rchl** [comment]
Fixing in https://github.com/typescript-language-server/typescript-language-server/pull/249

**Comment by duydang2311** [comment]
First of all, thank you for your time.
I've set the `"log_debug": true` and don't find any messages that say "ignoring unsuitable diagnostics for..." in the console (which is opened when pressing Ctrl+` if I am correct).
If you have identified the issue, I will test again to close this when your fix is merged and released.

**Comment by duydang2311** [comment]
Having found that your fix was merged, I updated my `typescript-language-server` version to `0.6.1` but the diagnostic still not making any difference.

**Comment by rchl** [comment]
How have you updated exactly. The version on https://packagecontrol.io/packages/LSP-typescript is not yet up-to-date.

**Comment by duydang2311** [comment]
Oh really, I thought I just need to update the `typescript-language-server` npm package version through the CLI.

**Comment by rchl** [comment]
No, that's not needed nor used. This package manages it itself.

**Comment by duydang2311** [comment]
I removed the Package Control's LSP-typescript and install it the manual way from this repo, now works like a charm!
Thank you for help!

**Comment by rchl** [comment]
Version v1.3.1 with the fix is now on package control.
