### ISSUE TITLE
Broken syntax highlight in .tsx files

### ISSUE THREAD

**Issue by mzaharie** [sublimelsp/LSP-typescript#81]
Using arrow functions with generic typing breaks the syntax highlighter.

See line 23 
<img width="603" alt="Screenshot 2021-08-18 at 11 36 31" src="https://user-images.githubusercontent.com/5528724/129866285-b183f8b4-4079-4e16-b3e0-b77c58fd87c3.png">

**Comment by rchl** [comment]
Syntax highlighting is not handled by this package.

Make sure you are using the built-in syntax from ST4 and not some other one. Remove packages `TypeScript` and `TypeScript Syntax` if you have those installed.

**Comment by mzaharie** [comment]
Only have `LSP-typescript`.  Then I guess it's from ST itself

**Comment by rchl** [comment]
If it's ST4 and you are using built-in TSX syntax then the https://github.com/sublimehq/Packages/issues would be the place to report it.
